[cisco_routers]
R1 ansible_host=192.168.40.10
R2 ansible_host=192.168.40.11
R3 ansible_host=192.168.40.12

[cisco_routers:vars]
ansible_connection=ansible.netcommon.network_cli
ansible_network_os=cisco.ios.ios
ansible_user=admin
