---
- name: Configure Cisco IOS interface
  cisco.ios.ios_interfaces:
    config:
      - name: "{{ cisco_ios_interface }}"
        description: "{{ cisco_ios_interface_description }}"
    state: "{{ cisco_ios_config_state }}"
